package process.sale.prototypes;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pikachu
 */
public class MainGui extends javax.swing.JFrame {
    RegisterController registerController;
    /**
     * Creates new form MainGui
     */
    public RegisterController getRegisterController(){
        return registerController;
    }
    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    public MainGui(Cashier cashier) {
        initComponents();
        centreWindow(this);
        SaleManager.getInstance();
        RentalManager.getInstance();
        CashierManager cashierManager = CashierManager.getInstance();
        if (cashier.getAccess()!=Cashier.Access.Admin){
            userManagementButton.setVisible(false);
            userManagementButton.setEnabled(false);
        }
        RegisterManager registerManager = RegisterManager.getInstance();
        Register register = new Register(registerManager.getNextId());
        register.setCashier(cashier);
        registerManager.addRegister(register);
        registerController = new RegisterController(register);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saleButton = new javax.swing.JButton();
        rentalButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        userManagementButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saleButton.setText("Sale");
        saleButton.setActionCommand("main1");
        saleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleButtonMouseClicked(evt);
            }
        });
        saleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleButtonActionPerformed(evt);
            }
        });

        rentalButton.setText("Rental");
        rentalButton.setActionCommand("main2");
        rentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.setActionCommand("main3");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        userManagementButton.setText("User Management");
        userManagementButton.setActionCommand("main4");
        userManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagementButtonActionPerformed(evt);
            }
        });

        changePasswordButton.setText("Change Password");
        changePasswordButton.setActionCommand("main4");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rentalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(userManagementButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(changePasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(saleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        saleButton.getAccessibleContext().setAccessibleName("main1");
        rentalButton.getAccessibleContext().setAccessibleName("main2");
        returnButton.getAccessibleContext().setAccessibleName("main3");
        userManagementButton.getAccessibleContext().setAccessibleName("main4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleButtonActionPerformed

    }//GEN-LAST:event_saleButtonActionPerformed

    private void saleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleButtonMouseClicked
        Object[] options = {"New",
                    "Suspended",
                    "Cancel"};
        int choice = JOptionPane.showOptionDialog(this,
            "New or Suspended?", "",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null, options, options[2]);

        switch(choice){
            case 0: 
                registerController.processSale();
                new SaleGUI(this).setVisible(true);
                this.setVisible(false);
                break;
            case 1:
                Sale sale = null;
                String inputValue;
                int id;
                do{
                    try{
                        inputValue = JOptionPane.showInputDialog("Return ID: "); 
                        id = Integer.parseInt(inputValue);
                        sale = SaleManager.getInstance().getSuspendedSaleById(id);
                    }catch(Exception e){
                    }
                }while(sale == null);
                registerController.processSuspendedSale(sale);
                new SaleGUI(this).setVisible(true);
                this.setVisible(false);
                break;
            default:
        }   
    }//GEN-LAST:event_saleButtonMouseClicked

    private void rentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalButtonActionPerformed
        Object[] options = {"New",
                    "Suspended",
                    "Cancel"};
        int choice = JOptionPane.showOptionDialog(this,
            "New or Suspended?", "",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null, options, options[2]);

        switch(choice){
            case 0: 
                registerController.processRental();
                this.setVisible(false);
                new RentalGUI(this).setVisible(true);
                break;
            case 1:
                Rental rental = null;
                String inputValue;
                int id;
                do{
                    try{
                        inputValue = JOptionPane.showInputDialog("Return ID: "); 
                        id = Integer.parseInt(inputValue);
                        rental = RentalManager.getInstance().getSuspendedRentalById(id);
                    }catch(Exception e){
                    }
                }while(rental == null);
                registerController.processSuspendedRental(rental);
                new RentalGUI(this).setVisible(true);
                this.setVisible(false);
                break;
            default:
        }   
    }//GEN-LAST:event_rentalButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        Object[] options = {"New Sale Return",
                    "Suspended Sale Return", "New Rental Return",
                    "Cancel"};
        int choice = JOptionPane.showOptionDialog(this,
            "New or Suspended?", "",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null, options, options[3]);
        String inputValue;
        int id;
        Sale sale = null;
        Rental rental = null;
        Return ret = null;
        switch(choice){
            case 0:
                do{
                    try{
                        inputValue = JOptionPane.showInputDialog("Sale ID: "); 
                        id = Integer.parseInt(inputValue);
                        sale = SaleManager.getInstance().getSaleById(id);
                    }catch(Exception e){
                    }
                }while(sale == null);
                registerController.processSaleReturn(sale);
                new ReturnGUI(this).setVisible(true);
                this.setVisible(false);
                break;
            case 1:
                do{
                    try{
                        inputValue = JOptionPane.showInputDialog("Return ID: "); 
                        id = Integer.parseInt(inputValue);
                        ret = ReturnManager.getInstance().getSuspendedReturnById(id);
                    }catch(Exception e){
                    }
                }while(ret == null);
                registerController.processSuspendedReturn(ret);
                new ReturnGUI(this).setVisible(true);
                this.setVisible(false);
                break;
            case 2:
                do{
                   try{
                        inputValue = JOptionPane.showInputDialog("Rental ID: "); 
                        id = Integer.parseInt(inputValue);
                        rental = RentalManager.getInstance().getRentalById(id);
                    }catch(Exception e){
                    }
                }while(rental == null);
                registerController.processRentalReturn(rental);
                new RentalReturnGUI(this).setVisible(true);
                this.setVisible(false);
                break;
        }   
    }//GEN-LAST:event_returnButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        new ChangePasswordGUI(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void userManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementButtonActionPerformed
        new UsermanagementGUI(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_userManagementButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainGui().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton rentalButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton saleButton;
    private javax.swing.JButton userManagementButton;
    // End of variables declaration//GEN-END:variables
}
